// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../remote/mock.go -package remote
//

// Package remote is a generated GoMock package.
package remote

import (
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteFetcher is a mock of RemoteFetcher interface.
type MockRemoteFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteFetcherMockRecorder
	isgomock struct{}
}

// MockRemoteFetcherMockRecorder is the mock recorder for MockRemoteFetcher.
type MockRemoteFetcherMockRecorder struct {
	mock *MockRemoteFetcher
}

// NewMockRemoteFetcher creates a new mock instance.
func NewMockRemoteFetcher(ctrl *gomock.Controller) *MockRemoteFetcher {
	mock := &MockRemoteFetcher{ctrl: ctrl}
	mock.recorder = &MockRemoteFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteFetcher) EXPECT() *MockRemoteFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockRemoteFetcher) Fetch(u *url.URL) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", u)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Fetch indicates an expected call of Fetch.
func (mr *MockRemoteFetcherMockRecorder) Fetch(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockRemoteFetcher)(nil).Fetch), u)
}
