// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../remote/mock.go -package remote
//

// Package remote is a generated GoMock package.
package remote

import (
	context "context"
	url "net/url"
	reflect "reflect"

	config "github.com/truewebber/golangcix/internal/domain/config"
	gomock "go.uber.org/mock/gomock"
)

// MockRemoteFetcher is a mock of RemoteFetcher interface.
type MockRemoteFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteFetcherMockRecorder
	isgomock struct{}
}

// MockRemoteFetcherMockRecorder is the mock recorder for MockRemoteFetcher.
type MockRemoteFetcherMockRecorder struct {
	mock *MockRemoteFetcher
}

// NewMockRemoteFetcher creates a new mock instance.
func NewMockRemoteFetcher(ctrl *gomock.Controller) *MockRemoteFetcher {
	mock := &MockRemoteFetcher{ctrl: ctrl}
	mock.recorder = &MockRemoteFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteFetcher) EXPECT() *MockRemoteFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockRemoteFetcher) Fetch(ctx context.Context, u *url.URL) (config.FetchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, u)
	ret0, _ := ret[0].(config.FetchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockRemoteFetcherMockRecorder) Fetch(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockRemoteFetcher)(nil).Fetch), ctx, u)
}
