// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mocks_test.go -package application_test
//

// Package application_test is a generated GoMock package.
package application_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockConfigLocator is a mock of ConfigLocator interface.
type MockConfigLocator struct {
	ctrl     *gomock.Controller
	recorder *MockConfigLocatorMockRecorder
	isgomock struct{}
}

// MockConfigLocatorMockRecorder is the mock recorder for MockConfigLocator.
type MockConfigLocatorMockRecorder struct {
	mock *MockConfigLocator
}

// NewMockConfigLocator creates a new mock instance.
func NewMockConfigLocator(ctrl *gomock.Controller) *MockConfigLocator {
	mock := &MockConfigLocator{ctrl: ctrl}
	mock.recorder = &MockConfigLocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigLocator) EXPECT() *MockConfigLocatorMockRecorder {
	return m.recorder
}

// Locate mocks base method.
func (m *MockConfigLocator) Locate(args []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locate", args)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locate indicates an expected call of Locate.
func (mr *MockConfigLocatorMockRecorder) Locate(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locate", reflect.TypeOf((*MockConfigLocator)(nil).Locate), args)
}

// MockConfigService is a mock of ConfigService interface.
type MockConfigService struct {
	ctrl     *gomock.Controller
	recorder *MockConfigServiceMockRecorder
	isgomock struct{}
}

// MockConfigServiceMockRecorder is the mock recorder for MockConfigService.
type MockConfigServiceMockRecorder struct {
	mock *MockConfigService
}

// NewMockConfigService creates a new mock instance.
func NewMockConfigService(ctrl *gomock.Controller) *MockConfigService {
	mock := &MockConfigService{ctrl: ctrl}
	mock.recorder = &MockConfigServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigService) EXPECT() *MockConfigServiceMockRecorder {
	return m.recorder
}

// Prepare mocks base method.
func (m *MockConfigService) Prepare(ctx context.Context, localConfigPath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", ctx, localConfigPath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prepare indicates an expected call of Prepare.
func (mr *MockConfigServiceMockRecorder) Prepare(ctx, localConfigPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockConfigService)(nil).Prepare), ctx, localConfigPath)
}

// MockLinter is a mock of Linter interface.
type MockLinter struct {
	ctrl     *gomock.Controller
	recorder *MockLinterMockRecorder
	isgomock struct{}
}

// MockLinterMockRecorder is the mock recorder for MockLinter.
type MockLinterMockRecorder struct {
	mock *MockLinter
}

// NewMockLinter creates a new mock instance.
func NewMockLinter(ctrl *gomock.Controller) *MockLinter {
	mock := &MockLinter{ctrl: ctrl}
	mock.recorder = &MockLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinter) EXPECT() *MockLinterMockRecorder {
	return m.recorder
}

// EnsureAvailable mocks base method.
func (m *MockLinter) EnsureAvailable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureAvailable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureAvailable indicates an expected call of EnsureAvailable.
func (mr *MockLinterMockRecorder) EnsureAvailable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureAvailable", reflect.TypeOf((*MockLinter)(nil).EnsureAvailable), ctx)
}

// Run mocks base method.
func (m *MockLinter) Run(ctx context.Context, args []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, args)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockLinterMockRecorder) Run(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockLinter)(nil).Run), ctx, args)
}
