package config

import (
	"path/filepath"
	"strings"
)

func GeneratedPath(localConfig string) string {
	dir := filepath.Dir(localConfig)
	if dir == "." {
		return GeneratedFileName
	}

	return filepath.Join(dir, GeneratedFileName)
}

func Header(remoteURL, localPath string) string {
	builder := &strings.Builder{}

	builder.WriteString("# WARNING: GENERATED FILE - DO NOT EDIT\n#\n\n")
	builder.WriteString("# Generated by golangci-wrapper.\n")
	builder.WriteString("# Local overrides: " + localPath + "\n")

	if remoteURL != "" {
		builder.WriteString("# Remote base: " + remoteURL + "\n")
	} else {
		builder.WriteString("# Remote base: not configured\n")
	}

	builder.WriteString("#\n\n")

	return builder.String()
}
