package config

import (
	"net/url"
	"path/filepath"
	"strings"
)

func GeneratedPath(localConfig string) string {
	dir := filepath.Dir(localConfig)
	if dir == "." {
		return GeneratedFileName
	}

	return filepath.Join(dir, GeneratedFileName)
}

func Header(remoteURL *url.URL, localPath string) string {
	builder := &strings.Builder{}

	builder.WriteString("# WARNING: GENERATED FILE - DO NOT EDIT\n#\n\n")
	builder.WriteString("# Generated by golangcix.\n")
	builder.WriteString("# Local overrides: " + localPath + "\n")

	if remoteURL != nil {
		builder.WriteString("# Remote base: " + remoteURL.String() + "\n")
	} else {
		builder.WriteString("# Remote base: not configured\n")
	}

	builder.WriteString("#\n\n")

	return builder.String()
}
