package config

import (
	"path/filepath"
)

func GeneratedPath(localConfig string) string {
	dir := filepath.Dir(localConfig)
	if dir == "." {
		return GeneratedFileName
	}
	return filepath.Join(dir, GeneratedFileName)
}

func Header(remoteURL, localPath string) string {
	header := "# WARNING: GENERATED FILE - DO NOT EDIT\n#\n"
	header += "# Generated by golangci-wrapper.\n"
	header += "# Local overrides: " + localPath + "\n"
	if remoteURL != "" {
		header += "# Remote base: " + remoteURL + "\n"
	} else {
		header += "# Remote base: not configured\n"
	}
	header += "#\n\n"
	return header
}
